@startuml
'https://plantuml.com/class-diagram

building_file --|> main
call_file --|> main
Elevator --|> main
Calls --|> main
main --|> output_file

file output_file{
}

file building_file{
}
file call_file{
}
class main {
}
class Elevator {

}
class Calls{
}

@enduml